name: Production Deploy
on:
  push:
    branches:
      - master
jobs:
  hasura_migration:
    name: Hasura migration and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Apply hasura migrations
        uses: GavinRay97/hasura-ci-cd-action@v1.3
        with:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_CLI_VERSION: v1.3.3
          HASURA_MIGRATIONS_ENABLED: true
          PATH_TO_HASURA_PROJECT_ROOT: ./hasura
      - name: Vercel Action
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: "--prod"
